### ISSUE TITLE
Files sometimes moved before transmission is finished with them

### ISSUE THREAD

**Issue by purefn** [Jonybat/flexget_config#16]
Ran into an issue where an episode was finished downloading, and it got moved by flexget out of the `downseries` directory and into the `series` directory. Problem is, transmission hadn't fully verified it yet and this caused the verification to fail, so it was never cleaned out properly.

Do you know of any workarounds for this?

**Comment by purefn** [comment]
By the way, thanks for sharing your configuration! I was upgrading from 1.2.x to 2.10.x and floundering trying to get my old configuration working. Yours does exactly what I wanted and is much cleaner!

**Comment by Jonybat** [comment]
That never happened to me. In what state does the torrent stays exactly?

**Comment by purefn** [comment]
It's probably a somewhat rare occurrence, although it did just happen a second time. The error is "Please Verify Local Data! Piece #0 is corrupt."

**Comment by Jonybat** [comment]
Oh, I've seen that some times in one of my flexget systems after all. Never paid much attention to it because in the end the downloaded file is fine. The only problem is like you said, it stays in transmission's queue until it's manually removed. 

I've only seen this in a low powered system tho, so I assume it has something to do with the amount of time that the verification process takes. I had 2 identical flexget setups and only happened in one of them. 

A quick fix from the top of my head could be to copy the files instead of moving them, and have a daily task/cron to clean the download folder.

**Comment by purefn** [comment]
Ah ok. It's not a big deal, really, just a slight annoyance. I also thought about hard linking the files, but it looks like FlexGet only has a support for symlinks. Probably running the `clean-transmission` task on a less regular basis would be good enough to decrease the likelihood of it occurring.

Thanks.

**Comment by Jonybat** [comment]
Like I said, I don't know for sure what causes this, but I'm inclined to believe it is the move tasks and clean source, not the clean transmission one.
