### ISSUE TITLE
Populate-series-db has no effect anymore

### ISSUE THREAD

**Issue by zilexa** [Jonybat/flexget_config#29]
Hi Jonybat, not sure if you still use Flexget. The forum seems quite deserted. 

I noticed `populate-series-db` has zero effect: Flexget will keep downloading episodes starting at the ep# set by `set-series-nextep`. Very annoying if you have a couple of seasons on your harddrive but only watched a few episodes. Overtime, I sometimes have each episode 4 times :(

I compared our configs and this part is exactly the same so I guess you might have the same issue.

**Comment by BrutuZ** [comment]
Coincidentally noticed the same a couple days ago.
While not sure as to why files found by `filesystem` input are no longer marked as seen in the series plugin, I managed to alleviate this by changing the context of `get-series-nextep` from **watched** to **collected** https://github.com/Jonybat/flexget_config/blob/78b9bb49aa0d3bfb0494febdb66bccfa9349a848/config.yml#L313
That worked for me since Plex also syncs the collection with Trakt. If that's not your case, it's safe to just disable the `*-nextep` scheduling to let Flexget keep track of the last episode on its own.
https://github.com/Jonybat/flexget_config/blob/78b9bb49aa0d3bfb0494febdb66bccfa9349a848/config.yml#L9
Maybe also manually set the series' begin with `flexget serie begin "series name" S03`

**Comment by Jonybat** [comment]
Yea I still use this, I just haven't updated anything in a long time because I've kinda reached the point where everything works as expected. Also, I haven't updated flexget past 2.11.21 because of a bug that still exists, so you might be experiencing some new bug. It worked last time I set it up for a friend, but again, was with v 2.11.21

**Comment by BrutuZ** [comment]
MAL hadn't worked for me in a long time, only manual entries in `anime.yml`, so I had to update because of the fix in [2.14.14](https://flexget.com/ChangeLog#21414-2018-08-02).

Traded in one bug for another, I guess =/

**Comment by Jonybat** [comment]
That's weird, MAL has been working fine here. There was only that couple of weeks when they had "maintenance" were nothing worked, but after that it started working again...

**Comment by zilexa** [comment]
I will uninstall the latest Flexget and install 11.21. it was also the last one I was using.

**Comment by ahuacate** [comment]
I am using docker repository "cpoppema/docker-flexget" - unfortunately a auto updating source and no tags. Can you provide me a source for a docker flexget 2.11.21?? 
I've been battling for a week to get Jonybats flexget config working with series 'identified_by: date' (i.e. The Daily Show) for a week throwing errors. Works fine with ep series

**Comment by marine1988** [comment]
any new on this mater ?

**Comment by zilexa** [comment]
I think Flexget development is dead. Even on the forum there has been no response to my requests to update the installation and update instructions.

**Comment by BrutuZ** [comment]
[Changelog](https://flexget.com/ChangeLog) says otherwise.
It's a open-source project, have you tried opening a PR with the desired changes?

**Comment by zilexa** [comment]
> 
> 
> Yea I still use this, I just haven't updated anything in a long time because I've kinda reached the point where everything works as expected. Also, I haven't updated flexget past 2.11.21 because of a bug that still exists, (...)

what bug(s) were you experiencing with newer versions?

**Comment by Jonybat** [comment]
https://github.com/Flexget/Flexget/issues/2071

**Comment by cvium** [comment]
https://github.com/Flexget/Flexget/pull/2286

**Comment by marine1988** [comment]
I was a good config but is outdated now!

**Comment by Jonybat** [comment]
I don't know what you mean with that comment, but this still works perfectly fine for me.
