### ISSUE TITLE
Howto begin series at other season than season 01

### ISSUE THREAD

**Issue by notDavid** [Jonybat/flexget_config#8]
Thanks for sharing this, very useful :) i have a question i was hoping you could help me with;
when browsing the Trakt website i can add a serie to my "series" list and Flexget will pick it up, that works great.
Now lets say i add "South Park", then Flexget will start downloading at Season01 Episode01.
However, i'd like to only download starting from Season 19 (and forever forward in the the future), can i do that from the Trakt website too?

Or is this only possible by manually running `flexget series begin "South Park" S19E01` from the commandline?

Thanks :)

**Comment by Jonybat** [comment]
Yup, its exactly how you describe it. This config is not tracking episodes from trakt, only series, so its not possible to know where to start.

I tried to implement it in the past but the trakt plugin was not working with episode tracking due to changes in trakt's api. Im not sure if this is still the case, but either way, its probably way too complicated for the little benefit it adds.

Yw :)

**Comment by notDavid** [comment]
okay thanks i thought so, just wanted to be sure i wasn't overlooking something... \o/
